### ISSUE TITLE
Outline Made

### ISSUE THREAD

**Issue by HarbingerOfFire** [HarbingerOfFire/PQC#2]
So I made an outline for the code, so it should work if implemented in place. What I could really use help on is the implementation of SHAKE128 (see. `SHAKE.h`) and the RBG (see. `random.h`). I will be working on an outline and some information about them and we can work on the encryption afterwards

**Comment by HarbingerOfFire** [comment]
@ScriptSlayer0 I've started with the XOF if you can make the RBG

**Comment by ScriptSlayer0** [comment]
I'm not at home to implement it, until Sunday when I can start working on it.

**Comment by HarbingerOfFire** [comment]
No worries, the XOF will take a bit to implement since I got to write the SHA-3 algorithm.

**Comment by HarbingerOfFire** [comment]
it looks like you're working on the SHAKE algorithm right now, which is the XOF for this. However, I'm over half-way done with it, so would you mind switching to creating the Random bit generator? 

> Randomness generation. Two algorithms in this standard require the generation of randomness
as an internal step: ML-KEM.KeyGen and ML-KEM.Encaps. (...) These random bytes shall be generated using an approved RBG, as prescribed in SP 800-90A, SP 800-90B, and SP 800-90C [18, 19, 20]. Moreover,this RBG shall have a security strength of at least 128 bits for ML-KEM-512, at least 192 bits for ML-KEM-768, and at least 256 bits for ML-KEM-1024.
> - FIPS 203

**Comment by ScriptSlayer0** [comment]
Go ahead with that I will get a review later.
Don't worry about that.

**Comment by HarbingerOfFire** [comment]
Ok, thanks. Just making sure we're on the same page.
