### ISSUE TITLE
Add OPENSSL for SHA3

### ISSUE THREAD

**Issue by HarbingerOfFire** [HarbingerOfFire/PQC#5]
I think we were having to many problems using our own implementation of SHA3 in this, so I changed to OPENSSL's implementation, which works really well.

Install for windows (24H2 with Choco): 
```
sudo choco install openssl
```

**Comment by HarbingerOfFire** [comment]
I have found that wolfSSL has started complying with FIPS 203, 204, and 205. I'm working with it right now to see what I can find.
Some notes so far:
when building and coming to the configure steps, include the flags `--enable-pqc --enable-keygen --enable-kyber --enable-dilithium`
When starting a new program, make sure to include `<wolfssl/options.h>` before the other options or it gives a warning about hardening options.

**Comment by HarbingerOfFire** [comment]
liboqs is also a dependancy

**Comment by HarbingerOfFire** [comment]
Looking into liboqs... we can't do this ourselves...

**Comment by HarbingerOfFire** [comment]
see: [dea9c8e](https://github.com/BivittatusDB/BDB-PQC/commit/dea9c8edeb89bac72dc0672eeec8e5e4d63e098f)

**Comment by ScriptSlayer0** [comment]
Are you using WSL or a virtual machine?

**Comment by HarbingerOfFire** [comment]
We should likely look into symcrypt for windows

**Comment by HarbingerOfFire** [comment]
Nevermind, I see installation instructions for windows with liboqs
